<a href="https://colab.research.google.com/github/morioka/BERT_Japanese_Google_Colaboratory/blob/master/4_BERT_livedoor_news_IIC_on_Google_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 日本語BERTでlivedoorニュースを相互情報量最大化(IIC)でクラスタリング

In [1]:
# 乱数シードの固定

import os
import random
import numpy as np
import torch

SEED_VALUE = 1234  # これはなんでも良い
os.environ['PYTHONHASHSEED'] = str(SEED_VALUE)
random.seed(SEED_VALUE)
np.random.seed(SEED_VALUE)
torch.manual_seed(SEED_VALUE)  # PyTorchを使う場合


### GPUの使用可能を確認

画面上部のメニュー ランタイム > ランタイムのタイプを変更 で、 ノートブックの設定 を開く

ハードウェアアクセラレータに GPU を選択し、 保存 する

In [2]:
# GPUの使用確認：True or False
torch.cuda.is_available()

# TrueならGPU使用可能

True

## 準備1：livedoorニュースをダウンロードして、PyTorchのDataLoaderに変換


In [3]:
# Livedoorニュースのファイルをダウンロード
! wget "https://www.rondhuit.com/download/ldcc-20140209.tar.gz"

--2021-04-23 15:48:35--  https://www.rondhuit.com/download/ldcc-20140209.tar.gz
Resolving www.rondhuit.com (www.rondhuit.com)... 59.106.19.174
Connecting to www.rondhuit.com (www.rondhuit.com)|59.106.19.174|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8855190 (8.4M) [application/x-gzip]
Saving to: ‘ldcc-20140209.tar.gz.1’

ldcc-20140209.tar.g 100%[===================>]   8.44M  4.06MB/s    in 2.1s    

2021-04-23 15:48:38 (4.06 MB/s) - ‘ldcc-20140209.tar.gz.1’ saved [8855190/8855190]



In [4]:
# ファイルを解凍し、カテゴリー数と内容を確認
import tarfile
import os

# 解凍
tar = tarfile.open("ldcc-20140209.tar.gz", "r:gz")
tar.extractall("./data/livedoor/")
tar.close()

# フォルダのファイルとディレクトリを確認
files_folders = [name for name in os.listdir("./data/livedoor/text/")]
print(files_folders)

# カテゴリーのフォルダのみを抽出
categories = [name for name in os.listdir(
    "./data/livedoor/text/") if os.path.isdir("./data/livedoor/text/"+name)]

print("カテゴリー数:", len(categories))
print(categories)


['peachy', 'movie-enter', 'smax', 'kaden-channel', 'livedoor-homme', 'it-life-hack', 'topic-news', 'sports-watch', 'README.txt', 'dokujo-tsushin', 'CHANGES.txt']
カテゴリー数: 9
['peachy', 'movie-enter', 'smax', 'kaden-channel', 'livedoor-homme', 'it-life-hack', 'topic-news', 'sports-watch', 'dokujo-tsushin']


In [5]:
# 本文を取得する前処理関数を定義


def extract_main_txt(file_name):
    with open(file_name) as text_file:
        # 今回はタイトル行は外したいので、3要素目以降の本文のみ使用
        text = text_file.readlines()[3:]

        # 3要素目以降にも本文が入っている場合があるので、リストにして、後で結合させる
        text = [sentence.strip() for sentence in text]  # 空白文字(スペースやタブ、改行)の削除
        text = list(filter(lambda line: line != '', text))
        text = ''.join(text)
        text = text.translate(str.maketrans(
            {'\n': '', '\t': '', '\r': '', '\u3000': ''}))  # 改行やタブ、全角スペースを消す
        return text


In [6]:
# リストに前処理した本文と、カテゴリーのラベルを追加していく
import glob

list_text = []
list_label = []

for cat in categories:
    text_files = glob.glob(os.path.join("./data/livedoor/text", cat, "*.txt"))

    # 前処理extract_main_txtを実施して本文を取得
    body = [extract_main_txt(text_file) for text_file in text_files]

    label = [cat] * len(body)  # bodyの数文だけカテゴリー名のラベルのリストを作成

    list_text.extend(body)  # appendが要素を追加するのに対して、extendはリストごと追加する
    list_label.extend(label)


In [7]:
# pandasのDataFrameにする
import pandas as pd

df = pd.DataFrame({'text': list_text, 'label': list_label})

# 大きさを確認しておく（7,376文章が存在）
print(df.shape)


(7376, 2)


In [8]:
# カテゴリーの辞書を作成
dic_id2cat = dict(zip(list(range(len(categories))), categories))
dic_cat2id = dict(zip(categories, list(range(len(categories)))))

# DataFrameにカテゴリーindexの列を作成
df["label_index"] = df["label"].map(dic_cat2id)

# label列を消去し、text, indexの順番にする
df = df.loc[:, ["text", "label_index"]]


In [9]:
# 順番をシャッフルする
df = df.sample(frac=1, random_state=123).reset_index(drop=True)


In [10]:
# tsvファイルで保存する

# 全体の2割の文章数
len_0_2 = len(df) // 5

# 前から2割をテストデータとする
df[:len_0_2].to_csv("./test.tsv", sep='\t', index=False, header=None)
print(df[:len_0_2].shape)

# 前2割からを訓練&検証データとする
df[len_0_2:].to_csv("./train_eval.tsv", sep='\t', index=False, header=None)
print(df[len_0_2:].shape)


(1475, 2)
(5901, 2)


In [11]:
# tsvファイルをダウンロードしたい場合
from google.colab import files

# ダウンロードする場合はコメントを外す
# 少し時間がかかる（4MB）
# files.download("./test.tsv")


# ダウンロードする場合はコメントを外す
# 少し時間がかかる（18MB）
# files.download("./train_eval.tsv")


- LivedoorニュースをBERT用のDataLoaderにする
- Hugginfaceのリポジトリの案内とは異なり、torchtextを使用した手法で実装

In [12]:
# MeCabとtransformersの用意
!apt install aptitude swig
!aptitude install mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file -y
!pip install mecab-python3
!pip install transformers==4.5.1
!pip install fugashi ipadic

Reading package lists... Done
Building dependency tree       
Reading state information... Done
aptitude is already the newest version (0.8.10-6ubuntu1).
swig is already the newest version (3.0.12-1).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
mecab is already installed at the requested version (0.996-5)
libmecab-dev is already installed at the requested version (0.996-5)
mecab-ipadic-utf8 is already installed at the requested version (2.7.0-20070801+main-1)
git is already installed at the requested version (1:2.17.1-1ubuntu0.8)
make is already installed at the requested version (4.1-9.1ubuntu1)
curl is already installed at the requested version (7.58.0-2ubuntu3.13)
xz-utils is already installed at the requested version (5.2.2-1.3)
file is already installed at the requested version (1:5.32-2ubuntu0.4)
mecab is already installed at the requested version (0.996-5)
libmecab-dev is already installed at the requested version (0.996-5)
mecab-ipadic-utf8 is already instal

In [13]:
!ln -s /etc/mecabrc /usr/local/etc/mecabrc

ln: failed to create symbolic link '/usr/local/etc/mecabrc': File exists


In [14]:
import torch
import torchtext.legacy as torchtext  # current 0.9.1 move Fields, Examples to legacy.
from transformers import BertModel
from transformers import BertJapaneseTokenizer

# 日本語BERTの分かち書き用tokenizerです
tokenizer = BertJapaneseTokenizer.from_pretrained(
    'cl-tohoku/bert-base-japanese-whole-word-masking')


In [15]:
# データを読み込んだときに、読み込んだ内容に対して行う処理を定義します

max_length = 512  # 東北大学_日本語版の最大の単語数（サブワード数）は512


def tokenizer_512(input_text):
    """torchtextのtokenizerとして扱えるように、512単語のpytorchでのencodeを定義。ここで[0]を指定し忘れないように"""
    return tokenizer.encode(input_text, max_length=512, return_tensors='pt')[0]


TEXT = torchtext.data.Field(sequential=True, tokenize=tokenizer_512, use_vocab=False, lower=False,
                            include_lengths=True, batch_first=True, fix_length=max_length, pad_token=0)
# 注意：tokenize=tokenizer.encodeと、.encodeをつけます。padding[PAD]のindexが0なので、0を指定します。

LABEL = torchtext.data.Field(sequential=False, use_vocab=False)

# (注釈)：各引数を再確認
# sequential: データの長さが可変か？文章は長さがいろいろなのでTrue.ラベルはFalse
# tokenize: 文章を読み込んだときに、前処理や単語分割をするための関数を定義
# use_vocab：単語をボキャブラリーに追加するかどうか
# lower：アルファベットがあったときに小文字に変換するかどうか
# include_length: 文章の単語数のデータを保持するか
# batch_first：ミニバッチの次元を用意するかどうか
# fix_length：全部の文章をfix_lengthと同じ長さになるように、paddingします
# init_token, eos_token, pad_token, unk_token：文頭、文末、padding、未知語に対して、どんな単語を与えるかを指定


In [16]:
# 各tsvファイルを読み込み、分かち書きをしてdatasetにします
# 少し時間がかかります
# train_eval：5901個、test：1475個
dataset_train_eval, dataset_test = torchtext.data.TabularDataset.splits(
    path='.', train='train_eval.tsv', test='test.tsv', format='tsv', fields=[('Text', TEXT), ('Label', LABEL)])



Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [17]:
# torchtext.data.Datasetのsplit関数で訓練データと検証データを分ける
# train_eval：5901個、test：1475個

dataset_train, dataset_eval = dataset_train_eval.split(
    split_ratio=1.0 - 1475/5901, random_state=random.seed(1234))

# datasetの長さを確認してみる
print(dataset_train.__len__())
print(dataset_eval.__len__())
print(dataset_test.__len__())


4426
1475
1475


In [18]:
# DataLoaderを作成します（torchtextの文脈では単純にiteraterと呼ばれています）
batch_size = 16  # BERTでは16、32あたりを使用する

dl_train = torchtext.data.Iterator(
    dataset_train, batch_size=batch_size, train=True)

dl_eval = torchtext.data.Iterator(
    dataset_eval, batch_size=batch_size, train=False, sort=False)

dl_test = torchtext.data.Iterator(
    dataset_test, batch_size=batch_size, train=False, sort=False)

# 辞書オブジェクトにまとめる
dataloaders_dict = {"train": dl_train, "val": dl_eval}


## 準備2：BERTでlivedoorニュースの記事をベクトル化する

In [19]:
from transformers import BertModel

# BERTの日本語学習済みパラメータのモデルです
model = BertModel.from_pretrained('cl-tohoku/bert-base-japanese-whole-word-masking')
model.eval()
print('ネットワーク設定完了')


ネットワーク設定完了


In [20]:
# BERTでベクトル化する関数を定義


def vectorize_with_bert(net, dataloader):

    # GPUが使えるかを確認
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print("使用デバイス：", device)
    print('-----start-------')

    # ネットワークをGPUへ
    net.to(device)

    # ネットワークがある程度固定であれば、高速化させる
    torch.backends.cudnn.benchmark = True

    # ミニバッチのサイズ
    batch_size = dataloader.batch_size

    # データローダーからミニバッチを取り出すループ
    for index, batch in enumerate(dataloader):
        # batchはTextとLableの辞書オブジェクト
        device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
        inputs = batch.Text[0].to(device)  # 文章
        labels = batch.Label.to(device)  # ラベル

        # 順伝搬（forward）計算
        with torch.set_grad_enabled(False):

            # Berに入力
            result = net(inputs)

            # sequence_outputの先頭の単語ベクトルを抜き出す
            vec_0 = result[0]  # 最初の0がsequence_outputを示す
            vec_0 = vec_0[:, 0, :]  # 全バッチ。先頭0番目の単語の全768要素
            vec_0 = vec_0.view(-1, 768)  # sizeを[batch_size, hidden_size]に変換

            # ベクトル化したデータをtorchリストにまとめる
            if index == 0:
                list_text = vec_0
                list_label = labels
            else:
                list_text = torch.cat([list_text, vec_0], dim=0)
                list_label = torch.cat([list_label, labels], dim=0)

    return list_text, list_label


In [21]:
# DataLoaderをベクトル化版に変換
# 少し時間がかかります5分弱

list_text_train, list_label_train = vectorize_with_bert(model, dl_train)
list_text_eval, list_label_eval = vectorize_with_bert(model, dl_eval)
list_text_test, list_label_test = vectorize_with_bert(model, dl_test)


使用デバイス： cuda:0
-----start-------
使用デバイス： cuda:0
-----start-------
使用デバイス： cuda:0
-----start-------


In [22]:
# torchのリストをDatasetに変換

from torch.utils.data import TensorDataset

dataset_bert_train = TensorDataset(
    list_label_train.view(-1, 1), list_text_train)
dataset_bert_eval = TensorDataset(list_label_eval.view(-1, 1), list_text_eval)
dataset_bert_test = TensorDataset(list_label_test.view(-1, 1), list_text_test)


In [23]:
# Dataloaderにする
from torch.utils.data import DataLoader

batch_size = 1024

dl_bert_train = DataLoader(
    dataset_bert_train, batch_size=batch_size, shuffle=True, drop_last=True)
# drop_lastは最後のミニバッチがbatch_sizeに足りない場合は無視する

dl_bert_eval = DataLoader(
    dataset_bert_eval, batch_size=batch_size, shuffle=False)
dl_bert_test = DataLoader(
    dataset_bert_test, batch_size=batch_size, shuffle=False)


## 準備3：IICのディープラーニングモデルを用意

In [24]:
import torch.nn as nn
import torch.nn.functional as F

OVER_CLUSTRING_RATE = 10


class NetIIC(nn.Module):
    def __init__(self):
        super(NetIIC, self).__init__()

        # multi-headは今回しない
        self.conv1 = nn.Conv1d(1, 400, kernel_size=768, stride=1, padding=0)
        self.bn1 = nn.BatchNorm1d(400)
        self.conv2 = nn.Conv1d(1, 300, kernel_size=400, stride=1, padding=0)
        self.bn2 = nn.BatchNorm1d(300)
        self.conv3 = nn.Conv1d(1, 300, kernel_size=300, stride=1, padding=0)
        self.bn3 = nn.BatchNorm1d(300)

        self.fc1 = nn.Linear(300, 250)
        self.bnfc1 = nn.BatchNorm1d(250)

        # livedoorニュースの9カテゴリに対応するかな？と期待する9分類
        self.fc2 = nn.Linear(250, 9)

        # overclustering
        # 実際の想定よりも多めにクラスタリングさせることで、ネットワークで微細な変化を捉えられるようにする
        self.fc2_overclustering = nn.Linear(250, 9*OVER_CLUSTRING_RATE)

    def forward(self, x):
        x = x.view(x.size(0), 1, -1)
        x = F.relu(self.bn1(self.conv1(x)))

        x = x.view(x.size(0), 1, -1)
        x = F.relu(self.bn2(self.conv2(x)))

        x = x.view(x.size(0), 1, -1)
        x = F.relu(self.bn3(self.conv3(x)))

        x = x.view(x.size(0), -1)
        x_prefinal = F.relu(self.bnfc1(self.fc1(x)))

        # multi-headは使わず
        y = F.softmax(self.fc2(x_prefinal), dim=1)
        y_overclustering = F.softmax(self.fc2_overclustering(
            x_prefinal), dim=1)  # overclustering

        return y, y_overclustering


In [25]:
import torch.nn.init as init


def weight_init(m):
    """重み初期化"""
    if isinstance(m, nn.Conv1d):
        init.normal_(m.weight.data)
        if m.bias is not None:
            init.normal_(m.bias.data)
    elif isinstance(m, nn.BatchNorm1d):
        init.normal_(m.weight.data, mean=1, std=0.02)
        init.constant_(m.bias.data, 0)
    elif isinstance(m, nn.Linear):
        # Xavier
        # init.xavier_normal_(m.weight.data)

        # He
        init.kaiming_normal_(m.weight.data)

        if m.bias is not None:
            init.normal_(m.bias.data)


In [26]:
# IISによる損失関数の定義
# 参考：https://github.com/RuABraun/phone-clustering/blob/master/mnist_basic.py
import sys


def compute_joint(x_out, x_tf_out):
    bn, k = x_out.size()
    assert (x_tf_out.size(0) == bn and x_tf_out.size(1) == k), '{} {} {} {}'.format(
        bn, k, x_tf_out.size(0), x_tf_out.size(1))

    p_i_j = x_out.unsqueeze(2) * x_tf_out.unsqueeze(1)  # bn, k, k
    p_i_j = p_i_j.sum(dim=0)  # k, k
    p_i_j = (p_i_j + p_i_j.t()) / 2.  # symmetrise
    p_i_j = p_i_j / p_i_j.sum()  # normalise
    return p_i_j


def IID_loss(x_out, x_tf_out, EPS=sys.float_info.epsilon):
    # has had softmax applied
    bs, k = x_out.size()
    p_i_j = compute_joint(x_out, x_tf_out)
    assert (p_i_j.size() == (k, k))

    p_i = p_i_j.sum(dim=1).view(k, 1).expand(k, k)
    p_j = p_i_j.sum(dim=0).view(1, k).expand(k, k)

    # avoid NaN losses. Effect will get cancelled out by p_i_j tiny anyway
    # これはPyTorchのバージョン1.3以上だとエラーになる
    # https://discuss.pytorch.org/t/pytorch-1-3-showing-an-error-perhaps-for-loss-computed-from-paired-outputs/68790/3
    #p_i_j[(p_i_j < EPS).data] = EPS
    #p_j[(p_j < EPS).data] = EPS
    #p_i[(p_i < EPS).data] = EPS

    p_i_j = torch.where(p_i_j < EPS, torch.tensor(
        [EPS], device=p_i_j.device), p_i_j)
    p_j = torch.where(p_j < EPS, torch.tensor([EPS], device=p_j.device), p_j)
    p_i = torch.where(p_i < EPS, torch.tensor([EPS], device=p_i.device), p_i)

    # https://qiita.com/Amanokawa/items/0aa24bc396dd88fb7d2a
    # 参考に、重みalphaを追加

    alpha = 2.0
    loss = (- p_i_j * (torch.log(p_i_j) - alpha *
                       torch.log(p_j) - alpha*torch.log(p_i))).sum()

    return loss


In [27]:
# データにノイズを加える関数の定義
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor_std = list_text_train.std(dim=0).to(device)


def perturb_data(x):
    y = x.clone()
    noise = torch.randn(len(tensor_std)).to(device)*tensor_std*2.0
    noise = noise.expand(x.shape[0], -1)
    y += noise

    return y


## 4：IICのネットワークを学習させる

In [28]:
# 学習関数の定義

def train(total_epoch, model, train_loader, optimizer, device):

    # ネットワークを訓練モードに
    model.train()

    # 学習率のスケジューラーCosAnnealing
    scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(
        optimizer, T_0=2, T_mult=2, eta_min=0)

    for epoch in range(total_epoch):
        for batch_idx, (target, data) in enumerate(train_loader):

            # 学習率変化
            scheduler.step()
            
            data_perturb = perturb_data(data)  # ノイズを与え、変換したデータを作る

            # GPUに送れる場合は送る
            data = data.to(device)
            data_perturb = data_perturb.to(device)

            # 最適化関数の初期化
            optimizer.zero_grad()

            # ニューラルネットワークへ入れる
            output, output_overclustering = model(data)
            output_perturb, output_perturb_overclustering = model(data_perturb)

            # 損失の計算
            loss1 = IID_loss(output, output_perturb)
            loss2 = IID_loss(output_overclustering,
                             output_perturb_overclustering)
            loss = loss1 + loss2

            # 損失を減らすように更新
            loss.backward()
            optimizer.step()

        # ログ出力
        if epoch % 50 == 0:
            print('Train Epoch {} \tLoss1: {:.6f} \tLoss2: {:.6f} \tLoss_total: {:.6f}'.format(
                epoch, loss1.item(), loss2.item(), loss1.item()+loss2.item()))

    return model, optimizer


In [29]:
# 学習の実施(5分弱)

# モデルの用意
net = NetIIC()
net.apply(weight_init)
net.to(device)

# 最適化関数
optimizer = torch.optim.Adam(net.parameters(), lr=5e-4) 

total_epoch = 1000

model_trained, optimizer = train(
    total_epoch, net, dl_bert_train, optimizer, device)


Train Epoch 0 	Loss1: -3.943261 	Loss2: -7.732243 	Loss_total: -11.675503
Train Epoch 50 	Loss1: -6.143390 	Loss2: -10.210949 	Loss_total: -16.354339
Train Epoch 100 	Loss1: -6.487886 	Loss2: -11.181625 	Loss_total: -17.669512
Train Epoch 150 	Loss1: -6.539138 	Loss2: -11.797247 	Loss_total: -18.336385
Train Epoch 200 	Loss1: -6.550503 	Loss2: -12.431877 	Loss_total: -18.982380
Train Epoch 250 	Loss1: -6.557390 	Loss2: -12.567236 	Loss_total: -19.124626
Train Epoch 300 	Loss1: -6.555585 	Loss2: -13.175591 	Loss_total: -19.731176
Train Epoch 350 	Loss1: -6.564304 	Loss2: -13.197260 	Loss_total: -19.761564
Train Epoch 400 	Loss1: -6.545244 	Loss2: -13.189154 	Loss_total: -19.734397
Train Epoch 450 	Loss1: -6.562121 	Loss2: -13.190464 	Loss_total: -19.752585
Train Epoch 500 	Loss1: -6.559155 	Loss2: -13.162882 	Loss_total: -19.722037
Train Epoch 550 	Loss1: -6.567320 	Loss2: -13.172867 	Loss_total: -19.740187
Train Epoch 600 	Loss1: -6.549450 	Loss2: -13.157639 	Loss_total: -19.707088
Tra

In [30]:
# モデル分類のクラスターの結果を確認する
import numpy as np

# ミニバッチサイズ1のテスト用のDataLoaderを用意
dl_bert_test = DataLoader(
    dataset_bert_test, batch_size=1, shuffle=False)


def test(model, device, test_loader):
    model.eval()

    out_targs = []
    ref_targs = []

    # 出力用のリストを用意
    total_num = len(test_loader)
    # index, (target_label, inferenced_label)
    output_list = np.zeros((total_num, 2))

    with torch.no_grad():
        for batch_idx, (target, data) in enumerate(test_loader):
            data = data.to(device)
            target = target.to(device)
            outputs, outputs_overclustering = model(data)

            # 分類結果をリストに追加
            out_targs.append(outputs.argmax(dim=1).cpu())
            ref_targs.append(target[0].cpu())

            # 結果をリストにまとめる
            output_list[batch_idx, 0] = target[0][0].cpu()  # 正解ラベル
            output_list[batch_idx, 1] = outputs.argmax(dim=1).cpu()  # 予測ラベル

    out_targs = torch.cat(out_targs)
    ref_targs = torch.cat(ref_targs)

    return out_targs.view(-1, 1).numpy(), ref_targs.numpy(), output_list


In [31]:
# テストデータで推論を実施
out_targs, ref_targs, output_list = test(model_trained, device, dl_bert_test)


In [32]:
# 混同行列（的な）を作る
matrix = np.zeros((9, 9))

# 縦にlivedoorニュースの正解クラスを、横に判定されたクラスの頻度表を作成
for i in range(len(out_targs)):
    row = ref_targs[i]
    col = out_targs[i]
    matrix[row][col] += 1

np.set_printoptions(suppress=True)
print(matrix)


[[  7.  11.   3.   3.  71.  10.  37.   2.  34.]
 [  7. 132.   0.   3.   3.   3.   4.  18.   4.]
 [  8.   1.   6. 100.   5.   3.  32.   0.   0.]
 [ 65.   0.  27.   8.  14.  31.  20.   3.   4.]
 [  8.   2.   7.   7.  40.   4.  19.   1.  14.]
 [ 21.   1.  30.  40.  22.  12.  40.   7.   3.]
 [ 39.   1.   0.   0.   1.  39.   1.  76.   0.]
 [ 62.   0.   0.   0.   0.  27.   0.  94.   0.]
 [  1.   5.   0.   0.  24.   2.   2.   3. 141.]]


In [33]:
dic_id2cat


{0: 'peachy',
 1: 'movie-enter',
 2: 'smax',
 3: 'kaden-channel',
 4: 'livedoor-homme',
 5: 'it-life-hack',
 6: 'topic-news',
 7: 'sports-watch',
 8: 'dokujo-tsushin'}

In [34]:
# クラスタの結果を確認
#「sports-watch」の5番目のクラスタの文章、7番目のクラスタの文章
#「topic-news」の5番目のクラスタの文章、7番目のクラスタの文章
# を確認して、クラスタ5とクラスタ7の特徴を見てみます。

import pandas as pd

df2 = pd.DataFrame(output_list)
df2.columns=["正解クラス", "推定クラスタ"]
df2.head()

正解クラス  推定クラスタ
0    5.0     6.0
1    6.0     0.0
2    3.0     0.0
3    6.0     7.0
4    5.0     4.0

In [35]:
df2[(df2['正解クラス']==0) & (df2['推定クラスタ']==5)].head()

正解クラス  推定クラスタ
180    0.0     5.0
646    0.0     5.0
703    0.0     5.0
792    0.0     5.0
812    0.0     5.0

In [36]:
# dfに元文書を入れている。300文字ほど見る。
print(df.iloc[21, 0][:300])
print(df.iloc[59, 0][:300])


Peachyでも大人気の「恋愛」をテーマにした記事の週間ランキングです！2012年5月24日〜5月30日の間にPeachyのアプリでみんなが読んだ恋愛記事TOP5をお届けします。第1位：職業がエロい、Ｆカップ…男友達に自慢したくなる彼女の特徴7選彼氏の男友達に紹介してもらえると、彼女としてひとつハードルを越えた気がしますよね。でも、なかなか紹介してもらえないと、「都合のいい女」の可能性がグッと上がります。彼氏が男友達に自慢したく彼女とは、いったいどんな女なのでしょうか。男性に本音で語ってもらいました。第2位：これだけは言わないで！男を幻滅させちゃう女のNG発言5つなぜ、あの人はあんなにモテるの
クリスマスシーズン到来！1年頑張った自分へのご褒美にプレゼントを、と考えている女子も多いはず！でも、この不況の中で外出も少なくなった今に、憧れのバッグや洋服はちょっと？と疑問の声も。そんな女子達に注目を浴びているのが、お部屋で“キレイ”を提供してくれるマジックボールなのです。神田うのさんの結婚式での引き出物として、スマッシュヒットとなったこのアイテム。現在でも、テレビドラマや関西空港のラウンジといった、上質空間で使用されており、ワンランク上の洗練度あふれるグッズとして人気は高まるばかり。その人気の秘密は、女子の心をくすぐるデザイン性と充実の機能から。デザインは、キュートな球体のフォルム。テーブ


In [37]:
df2[(df2['正解クラス']==0) & (df2['推定クラスタ']==7)].head(2)

正解クラス  推定クラスタ
973     0.0     7.0
1248    0.0     7.0

In [38]:
# dfに元文書を入れている。300文字ほど見る。
print(df.iloc[14, 0][:300])
print(df.iloc[18, 0][:300])

司法試験と並ぶ難関の国家試験で、好不況にかかわらず高い人気を誇る公認会計士というお仕事。今回、お茶の水女子大学在学中に公認会計士の資格を取得し、現在では経営コンサルタントとして様々なセミナーなどで講師としてもご活躍中の平林亮子さんに、会計士のお仕事内容を伺いました。「やっぱり“資格”だと思った」と話す平林さんが教える、成功の秘訣とは？——公認会計士になろうと思ったきっかけは？平林亮子（以下、平林）：入り口としてはすごく単純で、やっぱり“資格”かなと思ったからですね。何の資格？となった時に、色々な資格を並べてみた中から父が「会計士がいいんじゃない？」と言ったんですよ。色々な所で、このエピソードを
こだわりぬいた素材を、シェフの華麗な手さばきと共に味わう事ができる鉄板焼「恵比寿」。ウェスティンホテル東京の敷地内にあり、連日国内外から多くの人々が訪れ、美しい料理に舌鼓を打っています。そんな、「恵比寿」で弱冠22歳という若さで活躍している美人シェフが鴨田萌子さんです。今回は、シェフスタイルが凛々しい鴨田さんにお仕事を始めたきっかけ、様々な出会いについてお話を伺いました。「いつか料理のお仕事に就きたい…」と考えている女子は必読です！——現在、鴨田さんは毎晩お客様の前に立って腕を振るっていますが、料理を作ることに興味を持ったきっかけは何でしたか？鴨田：小さい頃から、人に喜んでもらうことが大好きで


In [39]:
df2[(df2['正解クラス']==8) & (df2['推定クラスタ']==5)].head(2)

正解クラス  推定クラスタ
921     8.0     5.0
1058    8.0     5.0

In [40]:
# dfに元文書を入れている。300文字ほど見る。
print(df.iloc[7, 0][:300])
print(df.iloc[55, 0][:300])

「目は口ほどにモノを言う」という言葉もあるように、目は重要なパーツであると同時に女子にとってもメイクに一番気合いが入るところ。最近ではまつ毛エクステも人気なのだが、つい欲張って“盛り”すぎちゃったり、クレンジング剤が限られてしまったりと、やはり塗るマスカラの使い勝手の良さにはかないません。そこで、デジャヴュが運営するサイト『シーン別まつげメイク塾』【PC版】【モバイル版】を実践してみました。『シーン別まつげメイク塾』では基本編「まつげメイクとは？」と、「浴衣」や「就活」、「合コン」とシーン別に分かれた応用編があり、誰でも楽しくマスカラメークを学ぶことができます。「夕方にはパンダ目になっちゃう」
6月に放映されたフジテレビ系バラエティ番組『人志松本のすべらない話』で、千原ジュニアが披露した「木村祐一兄さん」という話が、ネットを中心に話題になったのをご存じだろうか？その話とは、ジュニアと木村祐一が深夜に女性をナンパし、女性は木村祐一の家についてきた。木村祐一は当然その女性が“その気がある”と思ったが、当の女性は“そんなつもり”じゃなかった。それに激怒した木村祐一は、その女性に「帰れ！」と言いながら冷凍された鶏肉を投げつけた……というものである。ネットでは木村祐一の行為が「傷害罪だろ」「千原もなんでそんな話を面白おかしくできるのか」「これをOAしたテレビもおかしい」等、批難が殺到した。もち


In [41]:
df2[(df2['正解クラス']==8) & (df2['推定クラスタ']==7)].head(2)

正解クラス  推定クラスタ
49    8.0     7.0
55    8.0     7.0

In [42]:
# dfに元文書を入れている。300文字ほど見る。
print(df.iloc[71, 0][:300])
print(df.iloc[76, 0][:300])

恋愛がうまく行っている時に限って、別の男性が魅力的に見えてしまうことがある。ましてや、相手からアタックしてきた場合、女として悪い気持ちにはならないだろう。今回の相談者・メグミさん（女性/39歳）は現在お付き合いしている男性の他に、以前お付き合いをしていた彼とも遠距離恋愛中。悪いことをしている自覚はあるのに、どうしても一人に選びきれない場合、どうすればいいだろうか。二人の男性の本音を含め、江奈先生にスピリチュアル鑑定をしてもらった。【占い師】江奈先生（＠nifty電話占い・メール占い）＜相談内容＞今、好きな人がふたりいます。一人は現在の彼氏。もう一人は関係がうやむやになってしまった遠距離の彼氏…
ドラえもんは四次元ポケットからさまざまな道具を出してくれるが、実は独女のバッグの中にもあらゆるものが入っている。働く独女たちに、個性的なバッグの中身を教えてもらった。●ヘビー級！デジタルいろいろバッグWEB制作会社に勤務する静さん（36歳）のバッグの重さは2kgを優に超えるという。大きなトートバッグの中には、スマホ含む携帯電話2台とそれらの充電池、予備電池。さらに、MacBook AirとドコモのXi（もちろん充電器も）。いずれも趣味と仕事の両面で必需品だとか。まるで秋葉原で買い物をした外国人観光客!?「3.11以降、デジタルものの充電切れに備えるようになりました。今後は予備電池の負荷を減らす


文章を見ただけでは、あまり特徴は分かりませんね。。。

ただ、スポーツとニュースは、記事の雰囲気がとても似ていることは分かります。

これ以上に、IICされたクラスタの特徴をきちんと把握するには、

- wordcloudで単語の頻度の傾向を見てみる
- クラスタ文書の全ベクトルをいじいじして、なんらかクラスタのベクトルを作って、代表文書を決めたり近い単語を出す

などの操作が考えられます。

以上。